[build]
command = "echo 'google_maps_api_key: $GOOGLE_MAPS_API_KEY' >> _config.yml && jekyll build"
publish = "_site"

[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]
  checkPaths = ['/']
  resultMode = "warn"
